name: Deploy to GitHub Pages

on:
  push:
    branches: ["main", "master"]
  workflow_dispatch:

# Allow GitHub Pages to deploy
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Derive repo name and base for VITE_BASE
        run: |
          echo "REPO_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
          if [[ "${GITHUB_REPOSITORY#*/}" == *.github.io ]]; then
            echo "BASE=/" >> $GITHUB_ENV
            echo "Using base: / (user/organization page)"
          else
            echo "BASE=/${GITHUB_REPOSITORY#*/}/" >> $GITHUB_ENV
            echo "Using base: /${GITHUB_REPOSITORY#*/}/ (project page)"
          fi

      - name: Build
        env:
          VITE_BASE: ${{ env.BASE }}
        run: |
          npm run build

      - name: SPA 404 fallback (copy index.html)
        run: |
          cp dist/index.html dist/404.html

      - name: Disable Jekyll on Pages
        run: |
          touch dist/.nojekyll

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
